events {}

http {
    resolver 127.0.0.11 valid=10s;
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    server {
        listen 80;

        location / {
            proxy_pass http://gocalc:7000;
        }
    }
}

